name: Multi-Platform Build
permissions:
  contents: write      
  pull-requests: read  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: simulacrum-linux
            binary_extension: ""
          - os: windows-2025-vs2026 
            artifact_name: simulacrum-windows
            binary_extension: ".exe"
          - os: macos-15 
            artifact_name: simulacrum-macos
            binary_extension: ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Odin
        uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev 

      - name: Build Project
        run: |        
          odin build . -out:${{ matrix.artifact_name }}${{ matrix.binary_extension }} -o:speed

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}${{ matrix.binary_extension }}
          if-no-files-found: error